# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FoodDeliveryPOC' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FoodDeliveryPOC
	pod 'Moya', '~> 13.0'
    	pod 'ObjectMapper', '~> 3.5'
  	pod "EasyPeasy"
  	pod 'RxSwift'
  	pod 'RxCocoa'


  target 'FoodDeliveryPOCTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FoodDeliveryPOCUITests' do
    # Pods for testing
  end

end
